try
{
    //Methods
}
catch(Exception ex)
{
    Log(ex);
    throw;
}